[[proxy]]
rewrite = "/v1"
backend = "http://localhost:3000/v1"

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "style/input.css", "-o", "style/output.css", "--minify"]
